# Install third-party dependencies using Conda.
# ``` bash
#   conda env create -f environment.yml
#   conda activate quad
# ```
name: quad
# channels:
#   - conda-forge
#   - defaults
#   - lambouj
dependencies:
  - boost 
  - eigen
  - occt 7.8.1 novtk_he2768ca_103